"""
Central config for all 8 ML models.
Each entry describes how to load, preprocess, and call the model.
"""

import os

BASE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(BASE)   # workspace root

MODELS = {
    "mnist": {
        "name": "MNIST Digit Classifier",
        "type": "image",
        "input_label": "UPLOAD HANDWRITTEN DIGIT IMAGE",
        "output_key": "prediction",
        "extra_keys": ["confidence"],
        "model_path": os.path.join(ROOT, "EXP 2 MNIST", "ANNModel.h5"),
        "model_format": "h5",
        "endpoint": "/predict/mnist",
        "description": "ANN — classifies handwritten digits 0–9",
    },
    "catdog": {
        "name": "Cat vs Dog Classifier",
        "type": "image",
        "input_label": "UPLOAD CAT OR DOG IMAGE",
        "output_key": "prediction",
        "extra_keys": ["confidence"],
        "model_path": os.path.join(ROOT, "EXP 3 Cat Dog CNN", "backend", "cat_dog_MobileNet.h5"),
        "model_format": "h5",
        "endpoint": "/predict/catdog",
        "description": "MobileNet CNN — binary image classifier",
    },
    "emotion": {
        "name": "Emotion Detection",
        "type": "image",
        "input_label": "UPLOAD FACE IMAGE",
        "output_key": "prediction",
        "extra_keys": ["confidence"],
        "model_path": os.path.join(ROOT, "EXP 4 & 5 Emotion_Detection", "emotion_detection_project", "emotion_model.h5"),
        "model_format": "h5",
        "endpoint": "/predict/emotion",
        "description": "CNN — detects 7 facial emotions",
    },
    "sentiment": {
        "name": "Sentiment Analysis",
        "type": "text",
        "input_label": "ENTER MOVIE REVIEW",
        "input_placeholder": "Type a movie review here...",
        "output_key": "sentiment",
        "extra_keys": ["confidence"],
        "model_path": os.path.join(ROOT, "EXP 6 Sentiment Analysis", "imdb_rnn_model (1).h5"),
        "model_format": "h5",
        "endpoint": "/predict/sentiment",
        "description": "RNN — IMDB positive / negative sentiment",
    },
    "caption": {
        "name": "Image Captioning",
        "type": "image",
        "input_label": "UPLOAD IMAGE TO CAPTION",
        "output_key": "caption",
        "extra_keys": ["method"],
        "model_path": os.path.join(ROOT, "EXP 7 Image captioning", "image_captioning_model.h5"),
        "tokenizer_path": os.path.join(ROOT, "EXP 7 Image captioning", "tokenizer (1).pkl"),
        "model_format": "h5",
        "endpoint": "/predict/caption",
        "description": "VGG16 + LSTM — generates image captions",
    },
    "pos": {
        "name": "POS Tagger",
        "type": "text",
        "input_label": "ENTER SENTENCE",
        "input_placeholder": "The quick brown fox jumps over the lazy dog",
        "output_key": "tokens",
        "extra_keys": [],
        "model_path": os.path.join(ROOT, "EXP 8 POS", "pos_model.h5"),
        "model_format": "h5",
        "endpoint": "/predict/pos",
        "description": "BiLSTM — Penn Treebank POS tagging",
    },
    "lstm": {
        "name": "LSTM Text Predictor",
        "type": "text_multi",
        "input_label": "ENTER SEED TEXT",
        "input_placeholder": "Once upon a time",
        "extra_field_label": "WORDS TO PREDICT",
        "extra_field_default": "5",
        "output_key": "predictions",
        "extra_keys": [],
        "model_path": os.path.join(ROOT, "EXP 9 LSTM", "LSTM_model.h5"),
        "tokenizer_path": os.path.join(ROOT, "EXP 9 LSTM", "tokenizer.pickle"),
        "model_format": "h5",
        "endpoint": "/predict/lstm",
        "description": "LSTM — next-word sequence prediction",
    },
    "sms": {
        "name": "SMS Spam Detector",
        "type": "text",
        "input_label": "ENTER SMS MESSAGE",
        "input_placeholder": "Congratulations! You've won a free prize...",
        "output_key": "label",
        "extra_keys": ["confidence"],
        "model_path": os.path.join(ROOT, "EXP 10 SMS", "gru_model.keras"),
        "tokenizer_path": os.path.join(ROOT, "EXP 10 SMS", "GRU_Tokenizer.pkl"),
        "model_format": "keras",
        "endpoint": "/predict/sms",
        "description": "GRU — spam vs ham classifier",
    },
}
